/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sketchproject.mbapp.views.pos;

import com.sketchproject.mbapp.utility.BrowserControl;

/**
 *
 * @author Asus
 */
public class AboutScreen extends javax.swing.JPanel {

    /**
     * Creates new form AboutScreen
     */
    public AboutScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelLocation = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        titleApp = new javax.swing.JLabel();
        labelWeb = new javax.swing.JLabel();
        subtitleApp = new javax.swing.JLabel();
        labelContact = new javax.swing.JLabel();
        versionApp = new javax.swing.JLabel();
        description1 = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        description2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelPinterest = new javax.swing.JLabel();
        logoApp = new javax.swing.JLabel();
        labelTwitter = new javax.swing.JLabel();
        logoDeveloper = new javax.swing.JLabel();
        labelFacebook = new javax.swing.JLabel();
        labelSocial = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(214, 214, 214));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(83, 84, 87));
        jLabel1.setText("About Us");

        jLabel2.setForeground(new java.awt.Color(83, 84, 87));
        jLabel2.setText("Credit Title Developer and Application");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(590, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        labelLocation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLocation.setForeground(new java.awt.Color(90, 158, 226));
        labelLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconLocation.png"))); // NOI18N
        labelLocation.setText("  Jawa Street 6 No.5 Jember - JATIM");

        labelPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPhone.setForeground(new java.awt.Color(90, 158, 226));
        labelPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconPhone.png"))); // NOI18N
        labelPhone.setText("  +6285655479868");

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(90, 158, 226));
        labelEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconMail.png"))); // NOI18N
        labelEmail.setText("  support@sketchproject.com");

        titleApp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleApp.setText("Micro Business App : Point of Sale ");

        labelWeb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelWeb.setForeground(new java.awt.Color(90, 158, 226));
        labelWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconWeb.png"))); // NOI18N
        labelWeb.setText("  www.sketchproject.com");

        subtitleApp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtitleApp.setText("Persistance for Business Performance");

        labelContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelContact.setText("Contact");

        versionApp.setText("Version 0.1");

        description1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        description1.setText("Streamline the retail checkout process for your employees and customers. ");

        copyright.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        copyright.setText("© Copyright 2014 Sketch Project Studio Allright Reserved");

        description2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        description2.setText("Designed to be very easy to use for day-to-day operation");

        jLabel7.setText("®");

        labelPinterest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPinterest.setForeground(new java.awt.Color(90, 158, 226));
        labelPinterest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconPinterest.png"))); // NOI18N
        labelPinterest.setText("  Pin Our Design sketchdev");
        labelPinterest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelPinterest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPinterestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPinterestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelPinterestMouseExited(evt);
            }
        });

        logoApp.setBackground(new java.awt.Color(204, 204, 204));
        logoApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsPosApp/logo.png"))); // NOI18N

        labelTwitter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTwitter.setForeground(new java.awt.Color(90, 158, 226));
        labelTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconTwitter.png"))); // NOI18N
        labelTwitter.setText("  Follow @sketchprojectdev");
        labelTwitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelTwitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTwitterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelTwitterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelTwitterMouseExited(evt);
            }
        });

        logoDeveloper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/developer.png"))); // NOI18N

        labelFacebook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFacebook.setForeground(new java.awt.Color(90, 158, 226));
        labelFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconFacebook.png"))); // NOI18N
        labelFacebook.setText("  Like sketchproject");
        labelFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFacebookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelFacebookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelFacebookMouseExited(evt);
            }
        });

        labelSocial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSocial.setText("Social");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(logoDeveloper)
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(subtitleApp)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titleApp)
                                .addComponent(logoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7))
                        .addComponent(versionApp)
                        .addComponent(description1)
                        .addComponent(description2)
                        .addComponent(copyright)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelLocation)
                                .addComponent(labelPhone)
                                .addComponent(labelEmail)
                                .addComponent(labelContact)
                                .addComponent(labelWeb))
                            .addGap(140, 140, 140)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelSocial)
                                .addComponent(labelTwitter)
                                .addComponent(labelFacebook)
                                .addComponent(labelPinterest))))
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 522, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logoDeveloper)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(logoApp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(titleApp))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(16, 16, 16)))
                            .addGap(0, 0, 0)
                            .addComponent(subtitleApp)
                            .addGap(8, 8, 8)
                            .addComponent(versionApp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(description1)
                            .addGap(2, 2, 2)
                            .addComponent(description2)
                            .addGap(20, 20, 20)
                            .addComponent(copyright)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelContact)
                                .addComponent(labelSocial))))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelLocation)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelPhone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelEmail)
                            .addGap(7, 7, 7)
                            .addComponent(labelWeb))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelTwitter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelFacebook)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelPinterest)))
                    .addContainerGap(136, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelPinterestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPinterestMouseClicked
        BrowserControl.displayURL("https://www.pinterest.com/sketchdev");
    }//GEN-LAST:event_labelPinterestMouseClicked

    private void labelPinterestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPinterestMouseEntered
        labelPinterest.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_labelPinterestMouseEntered

    private void labelPinterestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPinterestMouseExited
        labelPinterest.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_labelPinterestMouseExited

    private void labelTwitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTwitterMouseClicked
        BrowserControl.displayURL("https://www.twitter.com/sketchprojectdev");
    }//GEN-LAST:event_labelTwitterMouseClicked

    private void labelTwitterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTwitterMouseEntered
        labelTwitter.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_labelTwitterMouseEntered

    private void labelTwitterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTwitterMouseExited
        labelTwitter.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_labelTwitterMouseExited

    private void labelFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFacebookMouseClicked
        BrowserControl.displayURL("https://www.facebook.com/page/sketchproject");
    }//GEN-LAST:event_labelFacebookMouseClicked

    private void labelFacebookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFacebookMouseEntered
        labelFacebook.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_labelFacebookMouseEntered

    private void labelFacebookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFacebookMouseExited
        labelFacebook.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_labelFacebookMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel description2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContact;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFacebook;
    private javax.swing.JLabel labelLocation;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelPinterest;
    private javax.swing.JLabel labelSocial;
    private javax.swing.JLabel labelTwitter;
    private javax.swing.JLabel labelWeb;
    private javax.swing.JLabel logoApp;
    private javax.swing.JLabel logoDeveloper;
    private javax.swing.JLabel subtitleApp;
    private javax.swing.JLabel titleApp;
    private javax.swing.JLabel versionApp;
    // End of variables declaration//GEN-END:variables
}
