/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sketchproject.mbapp.views.pos;

import com.sketchproject.mbapp.utility.BrowserControl;

/**
 *
 * @author Asus
 */
public class HelpScreen extends javax.swing.JPanel {

    /**
     * Creates new form HomeScreen
     */
    public HelpScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelVendor = new javax.swing.JLabel();
        labelVendorVersion = new javax.swing.JLabel();
        linkOpenHelp = new javax.swing.JLabel();
        labelSpecification = new javax.swing.JLabel();
        linkQuickSolution = new javax.swing.JLabel();
        labelVm = new javax.swing.JLabel();
        linkSearchInternet = new javax.swing.JLabel();
        iconSystem = new javax.swing.JLabel();
        labelCustomerCare = new javax.swing.JLabel();
        iconInformation = new javax.swing.JLabel();
        linkSupportRequest = new javax.swing.JLabel();
        iconService = new javax.swing.JLabel();
        linkSendFeedback = new javax.swing.JLabel();
        iconHelp = new javax.swing.JLabel();
        linkOurSite = new javax.swing.JLabel();
        iconApplication = new javax.swing.JLabel();
        labelLastUpdate = new javax.swing.JLabel();
        linkDeveloper = new javax.swing.JLabel();
        labelAdditional = new javax.swing.JLabel();
        linkAboutSketchProject = new javax.swing.JLabel();
        linkDeveloperServices = new javax.swing.JLabel();
        linkMeetOursTeam = new javax.swing.JLabel();
        labelSystem = new javax.swing.JLabel();
        labelOs = new javax.swing.JLabel();
        labelOsVersion = new javax.swing.JLabel();
        labelArch = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        labelApplication = new javax.swing.JLabel();
        labelCodename = new javax.swing.JLabel();
        labelHelp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(214, 214, 214));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(83, 84, 87));
        jLabel1.setText("Help and Support");

        jLabel2.setForeground(new java.awt.Color(83, 84, 87));
        jLabel2.setText("Contact and Response Our Services");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        labelVendor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVendor.setForeground(new java.awt.Color(90, 158, 226));
        labelVendor.setText("Oracle Technology");

        labelVendorVersion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVendorVersion.setForeground(new java.awt.Color(90, 158, 226));
        labelVendorVersion.setText("JDK 8.1");

        linkOpenHelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkOpenHelp.setForeground(new java.awt.Color(90, 158, 226));
        linkOpenHelp.setText("Open Help");
        linkOpenHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkOpenHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkOpenHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkOpenHelpMouseExited(evt);
            }
        });

        labelSpecification.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSpecification.setForeground(new java.awt.Color(90, 158, 226));
        labelSpecification.setText("JDK 8.1");

        linkQuickSolution.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkQuickSolution.setForeground(new java.awt.Color(90, 158, 226));
        linkQuickSolution.setText("Find Quick Solution");
        linkQuickSolution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkQuickSolution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkQuickSolutionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkQuickSolutionMouseExited(evt);
            }
        });

        labelVm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVm.setForeground(new java.awt.Color(90, 158, 226));
        labelVm.setText("Oracle Technology");

        linkSearchInternet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkSearchInternet.setForeground(new java.awt.Color(90, 158, 226));
        linkSearchInternet.setText("Search Internet Knoledgebase");
        linkSearchInternet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkSearchInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkSearchInternetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkSearchInternetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkSearchInternetMouseExited(evt);
            }
        });

        iconSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconChip.png"))); // NOI18N

        labelCustomerCare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCustomerCare.setText("Customer Care");

        iconInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconInfo.png"))); // NOI18N

        linkSupportRequest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkSupportRequest.setForeground(new java.awt.Color(90, 158, 226));
        linkSupportRequest.setText("Support Request");
        linkSupportRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkSupportRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkSupportRequestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkSupportRequestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkSupportRequestMouseExited(evt);
            }
        });

        iconService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconServices.png"))); // NOI18N

        linkSendFeedback.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkSendFeedback.setForeground(new java.awt.Color(90, 158, 226));
        linkSendFeedback.setText("Send Feedback");
        linkSendFeedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkSendFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkSendFeedbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkSendFeedbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkSendFeedbackMouseExited(evt);
            }
        });

        iconHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconQuestion.png"))); // NOI18N

        linkOurSite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkOurSite.setForeground(new java.awt.Color(90, 158, 226));
        linkOurSite.setText("Our Site");
        linkOurSite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkOurSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkOurSiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkOurSiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkOurSiteMouseExited(evt);
            }
        });

        iconApplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconComputer.png"))); // NOI18N

        labelLastUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLastUpdate.setText("Lastest Update :");

        linkDeveloper.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkDeveloper.setForeground(new java.awt.Color(90, 158, 226));
        linkDeveloper.setText("Click here");
        linkDeveloper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkDeveloper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkDeveloperMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkDeveloperMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkDeveloperMouseExited(evt);
            }
        });

        labelAdditional.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAdditional.setText("Additional Information");

        linkAboutSketchProject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkAboutSketchProject.setForeground(new java.awt.Color(90, 158, 226));
        linkAboutSketchProject.setText("About Sketch Project Studio");
        linkAboutSketchProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkAboutSketchProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkAboutSketchProjectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkAboutSketchProjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkAboutSketchProjectMouseExited(evt);
            }
        });

        linkDeveloperServices.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkDeveloperServices.setForeground(new java.awt.Color(90, 158, 226));
        linkDeveloperServices.setText("Developer Services");
        linkDeveloperServices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkDeveloperServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkDeveloperServicesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkDeveloperServicesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkDeveloperServicesMouseExited(evt);
            }
        });

        linkMeetOursTeam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkMeetOursTeam.setForeground(new java.awt.Color(90, 158, 226));
        linkMeetOursTeam.setText("Meets OursTeam");
        linkMeetOursTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkMeetOursTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkMeetOursTeamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkMeetOursTeamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkMeetOursTeamMouseExited(evt);
            }
        });

        labelSystem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSystem.setText("System Core");

        labelOs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelOs.setForeground(new java.awt.Color(90, 158, 226));
        labelOs.setText("You Running on Windows 7");

        labelOsVersion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelOsVersion.setForeground(new java.awt.Color(90, 158, 226));
        labelOsVersion.setText("Version: 6.1");

        labelArch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelArch.setForeground(new java.awt.Color(90, 158, 226));
        labelArch.setText("Arch: amd64");

        labelUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelUser.setForeground(new java.awt.Color(90, 158, 226));
        labelUser.setText("User : Angga");

        labelApplication.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelApplication.setText("Application");

        labelCodename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCodename.setForeground(new java.awt.Color(90, 158, 226));
        labelCodename.setText("Code Name Avia");

        labelHelp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelHelp.setText("Help");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconInformation)
                    .addComponent(iconHelp)
                    .addComponent(iconService))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linkAboutSketchProject)
                    .addComponent(linkDeveloperServices)
                    .addComponent(linkMeetOursTeam)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(linkOurSite)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(labelLastUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(linkDeveloper))
                            .addComponent(labelAdditional)
                            .addComponent(linkOpenHelp)
                            .addComponent(labelHelp)
                            .addComponent(labelCustomerCare)
                            .addComponent(linkSupportRequest)
                            .addComponent(linkSendFeedback)
                            .addComponent(linkQuickSolution)
                            .addComponent(linkSearchInternet))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconApplication)
                            .addComponent(iconSystem))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSystem)
                            .addComponent(labelOs)
                            .addComponent(labelOsVersion)
                            .addComponent(labelArch)
                            .addComponent(labelUser)
                            .addComponent(labelApplication)
                            .addComponent(labelCodename)
                            .addComponent(labelVendor)
                            .addComponent(labelVendorVersion)
                            .addComponent(labelVm)
                            .addComponent(labelSpecification))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelApplication)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelOs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelOsVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelArch)
                        .addGap(4, 4, 4)
                        .addComponent(labelUser)
                        .addGap(17, 17, 17)
                        .addComponent(labelSystem)
                        .addGap(7, 7, 7)
                        .addComponent(labelCodename)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVendor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVendorVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSpecification))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iconApplication)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iconSystem))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelHelp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(linkOpenHelp))
                                    .addComponent(iconHelp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linkQuickSolution)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linkSearchInternet)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCustomerCare)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(linkSupportRequest))
                                    .addComponent(iconService))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linkSendFeedback)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linkOurSite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLastUpdate)
                            .addComponent(linkDeveloper))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelAdditional)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linkAboutSketchProject))
                            .addComponent(iconInformation))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkDeveloperServices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkMeetOursTeam)
                .addGap(0, 65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void linkOpenHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOpenHelpMouseEntered
        linkOpenHelp.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkOpenHelpMouseEntered

    private void linkOpenHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOpenHelpMouseExited
        linkOpenHelp.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkOpenHelpMouseExited

    private void linkQuickSolutionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkQuickSolutionMouseEntered
        linkQuickSolution.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkQuickSolutionMouseEntered

    private void linkQuickSolutionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkQuickSolutionMouseExited
        linkQuickSolution.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkQuickSolutionMouseExited

    private void linkSearchInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSearchInternetMouseClicked
        BrowserControl.displayURL("https://www.google.co.id/search?q=credits");
    }//GEN-LAST:event_linkSearchInternetMouseClicked

    private void linkSearchInternetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSearchInternetMouseEntered
        linkSearchInternet.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkSearchInternetMouseEntered

    private void linkSearchInternetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSearchInternetMouseExited
        linkSearchInternet.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkSearchInternetMouseExited

    private void linkSupportRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSupportRequestMouseClicked
        BrowserControl.displayURL("http://microbusinessapp.sketchdeveloper.com/support");
    }//GEN-LAST:event_linkSupportRequestMouseClicked

    private void linkSupportRequestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSupportRequestMouseEntered
        linkSupportRequest.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkSupportRequestMouseEntered

    private void linkSupportRequestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSupportRequestMouseExited
        linkSupportRequest.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkSupportRequestMouseExited

    private void linkSendFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSendFeedbackMouseClicked
        BrowserControl.displayURL("http://microbusinessapp.sketchdeveloper.com/feedback");
    }//GEN-LAST:event_linkSendFeedbackMouseClicked

    private void linkSendFeedbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSendFeedbackMouseEntered
        linkSendFeedback.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkSendFeedbackMouseEntered

    private void linkSendFeedbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSendFeedbackMouseExited
        linkSendFeedback.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkSendFeedbackMouseExited

    private void linkOurSiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOurSiteMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com");
    }//GEN-LAST:event_linkOurSiteMouseClicked

    private void linkOurSiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOurSiteMouseEntered
        linkOurSite.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkOurSiteMouseEntered

    private void linkOurSiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOurSiteMouseExited
        linkOurSite.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkOurSiteMouseExited

    private void linkDeveloperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com/news");
    }//GEN-LAST:event_linkDeveloperMouseClicked

    private void linkDeveloperMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperMouseEntered
        linkDeveloper.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkDeveloperMouseEntered

    private void linkDeveloperMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperMouseExited
        linkDeveloper.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkDeveloperMouseExited

    private void linkAboutSketchProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkAboutSketchProjectMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com/about");
    }//GEN-LAST:event_linkAboutSketchProjectMouseClicked

    private void linkAboutSketchProjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkAboutSketchProjectMouseEntered
        linkAboutSketchProject.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkAboutSketchProjectMouseEntered

    private void linkAboutSketchProjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkAboutSketchProjectMouseExited
        linkAboutSketchProject.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkAboutSketchProjectMouseExited

    private void linkDeveloperServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperServicesMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com/services");
    }//GEN-LAST:event_linkDeveloperServicesMouseClicked

    private void linkDeveloperServicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperServicesMouseEntered
        linkDeveloperServices.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkDeveloperServicesMouseEntered

    private void linkDeveloperServicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperServicesMouseExited
        linkDeveloperServices.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkDeveloperServicesMouseExited

    private void linkMeetOursTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMeetOursTeamMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com/ourteam");
    }//GEN-LAST:event_linkMeetOursTeamMouseClicked

    private void linkMeetOursTeamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMeetOursTeamMouseEntered
        linkMeetOursTeam.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkMeetOursTeamMouseEntered

    private void linkMeetOursTeamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMeetOursTeamMouseExited
        linkMeetOursTeam.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkMeetOursTeamMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconApplication;
    private javax.swing.JLabel iconHelp;
    private javax.swing.JLabel iconInformation;
    private javax.swing.JLabel iconService;
    private javax.swing.JLabel iconSystem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAdditional;
    private javax.swing.JLabel labelApplication;
    private javax.swing.JLabel labelArch;
    private javax.swing.JLabel labelCodename;
    private javax.swing.JLabel labelCustomerCare;
    private javax.swing.JLabel labelHelp;
    private javax.swing.JLabel labelLastUpdate;
    private javax.swing.JLabel labelOs;
    private javax.swing.JLabel labelOsVersion;
    private javax.swing.JLabel labelSpecification;
    private javax.swing.JLabel labelSystem;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelVendor;
    private javax.swing.JLabel labelVendorVersion;
    private javax.swing.JLabel labelVm;
    private javax.swing.JLabel linkAboutSketchProject;
    private javax.swing.JLabel linkDeveloper;
    private javax.swing.JLabel linkDeveloperServices;
    private javax.swing.JLabel linkMeetOursTeam;
    private javax.swing.JLabel linkOpenHelp;
    private javax.swing.JLabel linkOurSite;
    private javax.swing.JLabel linkQuickSolution;
    private javax.swing.JLabel linkSearchInternet;
    private javax.swing.JLabel linkSendFeedback;
    private javax.swing.JLabel linkSupportRequest;
    // End of variables declaration//GEN-END:variables
}
