/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sketchproject.mbapp.views;

import com.sketchproject.mbapp.core.Config;
import com.sketchproject.mbapp.utility.BCrypt;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Asus
 */
public class Lockscreen extends javax.swing.JDialog {

    /** Creates new form Lockscreen */
    public Lockscreen(java.awt.Frame parent) {        
        super(parent, true);
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        
        initComponents();
        setLocationRelativeTo(parent);
        
        user.setText(Config.userName);
        
        password.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode()== 10){
                    if (BCrypt.checkpw(new String(password.getPassword()), Config.hashPassword)){
                        dispose();
                    }
                    else{
                        status.setText("Password Missmatch with active user");
                        password.setText(null);
                    }
                }
            }            
        });
        
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        user = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(null);

        status.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(status);
        status.setBounds(230, 312, 270, 20);

        password.setText("type a password");
        password.setBorder(null);
        password.setOpaque(false);
        jPanel1.add(password);
        password.setBounds(240, 280, 230, 20);

        user.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("ANGGA ARI WIJAYA");
        jPanel1.add(user);
        user.setBounds(230, 230, 310, 40);

        background.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/LockScreen.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 600, 400);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel status;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

}
