/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sketchproject.mbapp.views;

import java.awt.Point;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;

/**
 *
 * @author Asus
 */
public class MenuScreen extends javax.swing.JFrame {

    private Point initialClick;
    
    /**
     * Creates new form MenuScreen
     */
    public MenuScreen() {
        initComponents();
        setLocationRelativeTo(null);
        
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                initialClick = e.getPoint();
                getComponentAt(initialClick);
            }
        });
        
        addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {

                // get location of Window
                int thisX = getLocation().x;
                int thisY = getLocation().y;

                // Determine how much the mouse moved since the initial click
                int xMoved = (thisX + e.getX()) - (thisX + initialClick.x);
                int yMoved = (thisY + e.getY()) - (thisY + initialClick.y);

                // Move window to this position
                int X = thisX + xMoved;
                int Y = thisY + yMoved;
                setLocation(X, Y);
            }
        });
    }
    
    public void setUser(String user){
        labelName.setText(user);
    }

    public void setListenerPos(ActionListener listener){
        buttonPos.addActionListener(listener);
    }
    
    public void setListenerCredit(ActionListener listener){
        buttonCredit.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        buttonCredit = new javax.swing.JButton();
        buttonPos = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Micro Business App Menu");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/ButtonCrossWhite.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 10, 30, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gambirono - Bangsalsari");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 460, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jl. Moch. Seruji 2/8");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 460, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UD. SISWANTO MOTOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 460, 40);

        labelName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelName.setText("Angga Ari Wijaya");
        getContentPane().add(labelName);
        labelName.setBounds(30, 360, 210, 30);

        buttonCredit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/ButtonAppCredits.png"))); // NOI18N
        buttonCredit.setBorderPainted(false);
        buttonCredit.setContentAreaFilled(false);
        buttonCredit.setFocusPainted(false);
        buttonCredit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/ButtonAppCreditsHover.png"))); // NOI18N
        getContentPane().add(buttonCredit);
        buttonCredit.setBounds(420, 290, 150, 120);

        buttonPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/ButtonAppShowroom.png"))); // NOI18N
        buttonPos.setBorderPainted(false);
        buttonPos.setContentAreaFilled(false);
        buttonPos.setFocusPainted(false);
        buttonPos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/ButtonAppShowroomHover.png"))); // NOI18N
        getContentPane().add(buttonPos);
        buttonPos.setBounds(250, 290, 150, 120);

        background.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/MenuBackground.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 599, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton buttonCredit;
    private javax.swing.JButton buttonPos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
