/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sketchproject.mbapp.views;

import java.awt.event.ActionEvent;

/**
 *
 * @author Asus
 */
public class NativeDialog extends javax.swing.JDialog {
    public static final String DIALOG_QUESTION = "question";
    public static final String DIALOG_INFORMATION = "information";
    
    public static final int PRIMARY_SELECT = 1;
    public static final int SECONDARY_SELECT = 2;
    public int select;
    
    /** Creates new form NativeDialog
     * @param parent
     * @param title
     * @param message
     * @param type */
    public NativeDialog(java.awt.Frame parent, String title, String message, String type) {
        super(parent, true);
        initComponents();
        
        dialogTitle.setText(title);
        dialogMessage.setText(message);
        
        setLocationRelativeTo(parent);
        
        buttonClose.addActionListener((ActionEvent e) -> {
            select = 2;
            dispose();
        });
        
        buttonPrimary.addActionListener((ActionEvent e) -> {
            select = 1;
            dispose();
        });
        
        buttonSecondary.addActionListener((ActionEvent e) -> {
            select = 2;
            dispose();
        });
        
        if(type.equals(DIALOG_INFORMATION)){
            panelButton.setLayout(new java.awt.GridLayout(1, 1));
            panelButton.remove(buttonSecondary);    
            
            buttonPrimary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsCreditApp/ButtonOk.png")));
            buttonPrimary.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsCreditApp/ButtonOkHover.png")));
        }
    }
    
    public int showDialog(){
        setVisible(true);
        return select;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDialog = new javax.swing.JPanel();
        dialogMessage = new javax.swing.JLabel();
        panelButton = new javax.swing.JPanel();
        buttonSecondary = new javax.swing.JButton();
        buttonPrimary = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        dialogTitle = new javax.swing.JLabel();
        buttonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);

        panelDialog.setBackground(new java.awt.Color(255, 255, 255));
        panelDialog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dialogMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dialogMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dialogMessage.setText("Are you sure want to exit ?");

        panelButton.setBackground(new java.awt.Color(255, 255, 255));
        panelButton.setLayout(new java.awt.GridLayout(1, 2));

        buttonSecondary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsCreditApp/ButtonNo.png"))); // NOI18N
        buttonSecondary.setBorderPainted(false);
        buttonSecondary.setContentAreaFilled(false);
        buttonSecondary.setFocusPainted(false);
        buttonSecondary.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsCreditApp/ButtonNoHover.png"))); // NOI18N
        panelButton.add(buttonSecondary);

        buttonPrimary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsCreditApp/ButtonYes.png"))); // NOI18N
        buttonPrimary.setBorderPainted(false);
        buttonPrimary.setContentAreaFilled(false);
        buttonPrimary.setFocusPainted(false);
        buttonPrimary.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsCreditApp/ButtonYesHover.png"))); // NOI18N
        panelButton.add(buttonPrimary);

        javax.swing.GroupLayout panelDialogLayout = new javax.swing.GroupLayout(panelDialog);
        panelDialog.setLayout(panelDialogLayout);
        panelDialogLayout.setHorizontalGroup(
            panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDialogLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDialogLayout.setVerticalGroup(
            panelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(dialogMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dialogTitle.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        dialogTitle.setText("Dialog Title");

        buttonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/ButtonCrossBlue.png"))); // NOI18N
        buttonClose.setBorderPainted(false);
        buttonClose.setContentAreaFilled(false);
        buttonClose.setFocusPainted(false);

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(dialogTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialogTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonPrimary;
    private javax.swing.JButton buttonSecondary;
    private javax.swing.JLabel dialogMessage;
    private javax.swing.JLabel dialogTitle;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelDialog;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables

}
