/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sketchproject.mbapp.views.credit;

import com.sketchproject.mbapp.utility.BrowserControl;

/**
 *
 * @author Asus
 */
public class AboutScreen extends javax.swing.JPanel {

    /** Creates new form HomeScreen */
    public AboutScreen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titleApp = new javax.swing.JLabel();
        subtitleApp = new javax.swing.JLabel();
        versionApp = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logoApp = new javax.swing.JLabel();
        logoDeveloper = new javax.swing.JLabel();
        labelSocial = new javax.swing.JLabel();
        labelLocation = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelWeb = new javax.swing.JLabel();
        labelContact = new javax.swing.JLabel();
        description1 = new javax.swing.JLabel();
        description2 = new javax.swing.JLabel();
        labelPinterest = new javax.swing.JLabel();
        labelTwitter = new javax.swing.JLabel();
        labelFacebook = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Credit Title Developer and Application");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("About Us");

        titleApp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleApp.setText("Micro Business App : Credits ");

        subtitleApp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtitleApp.setText("Persistance for Business Performance");

        versionApp.setText("Version 0.1");

        copyright.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        copyright.setText("© Copyright 2014 Sketch Project Studio Allright Reserved");

        jLabel7.setText("®");

        logoApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsCreditApp/logo.png"))); // NOI18N

        logoDeveloper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/developer.png"))); // NOI18N

        labelSocial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSocial.setText("Social");

        labelLocation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLocation.setForeground(new java.awt.Color(90, 158, 226));
        labelLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconLocation.png"))); // NOI18N
        labelLocation.setText("  Jawa Street 6 No.5 Jember - JATIM");

        labelPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPhone.setForeground(new java.awt.Color(90, 158, 226));
        labelPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconPhone.png"))); // NOI18N
        labelPhone.setText("  +6285655479868");

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(90, 158, 226));
        labelEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconMail.png"))); // NOI18N
        labelEmail.setText("  support@sketchproject.com");

        labelWeb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelWeb.setForeground(new java.awt.Color(90, 158, 226));
        labelWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconWeb.png"))); // NOI18N
        labelWeb.setText("  www.sketchproject.com");

        labelContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelContact.setText("Contact");

        description1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        description1.setText("Use Micro Business App : Credits to monitor and track your credit score progress.");

        description2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        description2.setText("Featured by Credit Report Card to identify areas to improve, and continue to track it over time. ");

        labelPinterest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPinterest.setForeground(new java.awt.Color(90, 158, 226));
        labelPinterest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconPinterest.png"))); // NOI18N
        labelPinterest.setText("  Pin Our Design sketchdev");
        labelPinterest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelPinterest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPinterestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPinterestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelPinterestMouseExited(evt);
            }
        });

        labelTwitter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTwitter.setForeground(new java.awt.Color(90, 158, 226));
        labelTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconTwitter.png"))); // NOI18N
        labelTwitter.setText("  Follow @sketchprojectdev");
        labelTwitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelTwitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTwitterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelTwitterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelTwitterMouseExited(evt);
            }
        });

        labelFacebook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFacebook.setForeground(new java.awt.Color(90, 158, 226));
        labelFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconFacebook.png"))); // NOI18N
        labelFacebook.setText("  Like sketchproject");
        labelFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFacebookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelFacebookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelFacebookMouseExited(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(logoDeveloper)
                        .add(42, 42, 42)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(subtitleApp)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(titleApp)
                                    .add(logoApp))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel7))
                            .add(versionApp)
                            .add(description1)
                            .add(description2)
                            .add(copyright)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(labelLocation)
                                    .add(labelPhone)
                                    .add(labelEmail)
                                    .add(labelContact)
                                    .add(labelWeb))
                                .add(140, 140, 140)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(labelSocial)
                                    .add(labelTwitter)
                                    .add(labelFacebook)
                                    .add(labelPinterest)))))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(0, 0, 0)
                .add(jLabel2)
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(logoDeveloper)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(logoApp)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(titleApp))
                            .add(layout.createSequentialGroup()
                                .add(jLabel7)
                                .add(16, 16, 16)))
                        .add(0, 0, 0)
                        .add(subtitleApp)
                        .add(8, 8, 8)
                        .add(versionApp)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(description1)
                        .add(2, 2, 2)
                        .add(description2)
                        .add(20, 20, 20)
                        .add(copyright)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelContact)
                            .add(labelSocial))))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(labelLocation)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelPhone)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelEmail)
                        .add(7, 7, 7)
                        .add(labelWeb))
                    .add(layout.createSequentialGroup()
                        .add(labelTwitter)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelFacebook)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelPinterest)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelTwitterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTwitterMouseEntered
        labelTwitter.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_labelTwitterMouseEntered

    private void labelTwitterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTwitterMouseExited
        labelTwitter.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_labelTwitterMouseExited

    private void labelFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFacebookMouseClicked
        BrowserControl.displayURL("https://www.facebook.com/page/sketchproject");
    }//GEN-LAST:event_labelFacebookMouseClicked

    private void labelTwitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTwitterMouseClicked
        BrowserControl.displayURL("https://www.twitter.com/sketchprojectdev");
    }//GEN-LAST:event_labelTwitterMouseClicked

    private void labelFacebookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFacebookMouseEntered
        labelFacebook.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_labelFacebookMouseEntered

    private void labelFacebookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFacebookMouseExited
        labelFacebook.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_labelFacebookMouseExited

    private void labelPinterestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPinterestMouseEntered
        labelPinterest.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_labelPinterestMouseEntered

    private void labelPinterestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPinterestMouseExited
        labelPinterest.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_labelPinterestMouseExited

    private void labelPinterestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPinterestMouseClicked
        BrowserControl.displayURL("https://www.pinterest.com/sketchdev");
    }//GEN-LAST:event_labelPinterestMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel description2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelContact;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFacebook;
    private javax.swing.JLabel labelLocation;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelPinterest;
    private javax.swing.JLabel labelSocial;
    private javax.swing.JLabel labelTwitter;
    private javax.swing.JLabel labelWeb;
    private javax.swing.JLabel logoApp;
    private javax.swing.JLabel logoDeveloper;
    private javax.swing.JLabel subtitleApp;
    private javax.swing.JLabel titleApp;
    private javax.swing.JLabel versionApp;
    // End of variables declaration//GEN-END:variables

}
