/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sketchproject.mbapp.views.credit;

import com.sketchproject.mbapp.core.Config;
import com.sketchproject.mbapp.utility.BrowserControl;
import com.sketchproject.mbapp.utility.SystemInfo;

/**
 *
 * @author Asus
 */
public class HelpScreen extends javax.swing.JPanel {

    /** Creates new form HomeScreen */
    public HelpScreen() {
        initComponents();
        
        labelOs.setText("Running on "+SystemInfo.getOS());
        labelOsVersion.setText("Version : "+SystemInfo.getVersion());
        labelArch.setText("Architecture : "+SystemInfo.getArchitecture());
        labelUser.setText("User : "+SystemInfo.getUser());
        
        labelCodename.setText("Codename : "+Config.CODENAME);
        labelVendor.setText(SystemInfo.getVendor());
        labelVendorVersion.setText("Vendor Version : "+SystemInfo.getVendorVersion());
        labelVm.setText(SystemInfo.getVm());
        labelSpecification.setText(SystemInfo.getSpecification());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelHelp = new javax.swing.JLabel();
        linkOpenHelp = new javax.swing.JLabel();
        linkQuickSolution = new javax.swing.JLabel();
        linkSearchInternet = new javax.swing.JLabel();
        labelCustomerCare = new javax.swing.JLabel();
        linkSupportRequest = new javax.swing.JLabel();
        linkSendFeedback = new javax.swing.JLabel();
        linkOurSite = new javax.swing.JLabel();
        labelLastUpdate = new javax.swing.JLabel();
        linkDeveloper = new javax.swing.JLabel();
        labelAdditional = new javax.swing.JLabel();
        linkAboutSketchProject = new javax.swing.JLabel();
        linkDeveloperServices = new javax.swing.JLabel();
        linkMeetOursTeam = new javax.swing.JLabel();
        labelSystem = new javax.swing.JLabel();
        labelOs = new javax.swing.JLabel();
        labelOsVersion = new javax.swing.JLabel();
        labelArch = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        labelApplication = new javax.swing.JLabel();
        labelCodename = new javax.swing.JLabel();
        labelVendor = new javax.swing.JLabel();
        labelVendorVersion = new javax.swing.JLabel();
        labelSpecification = new javax.swing.JLabel();
        labelVm = new javax.swing.JLabel();
        iconSystem = new javax.swing.JLabel();
        iconInformation = new javax.swing.JLabel();
        iconService = new javax.swing.JLabel();
        iconHelp = new javax.swing.JLabel();
        iconApplication = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Contact and Response Our Services");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Help and Support");

        labelHelp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelHelp.setText("Help");

        linkOpenHelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkOpenHelp.setForeground(new java.awt.Color(90, 158, 226));
        linkOpenHelp.setText("Open Help");
        linkOpenHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkOpenHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkOpenHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkOpenHelpMouseExited(evt);
            }
        });

        linkQuickSolution.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkQuickSolution.setForeground(new java.awt.Color(90, 158, 226));
        linkQuickSolution.setText("Find Quick Solution");
        linkQuickSolution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkQuickSolution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkQuickSolutionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkQuickSolutionMouseExited(evt);
            }
        });

        linkSearchInternet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkSearchInternet.setForeground(new java.awt.Color(90, 158, 226));
        linkSearchInternet.setText("Search Internet Knoledgebase");
        linkSearchInternet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkSearchInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkSearchInternetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkSearchInternetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkSearchInternetMouseExited(evt);
            }
        });

        labelCustomerCare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCustomerCare.setText("Customer Care");

        linkSupportRequest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkSupportRequest.setForeground(new java.awt.Color(90, 158, 226));
        linkSupportRequest.setText("Support Request");
        linkSupportRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkSupportRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkSupportRequestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkSupportRequestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkSupportRequestMouseExited(evt);
            }
        });

        linkSendFeedback.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkSendFeedback.setForeground(new java.awt.Color(90, 158, 226));
        linkSendFeedback.setText("Send Feedback");
        linkSendFeedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkSendFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkSendFeedbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkSendFeedbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkSendFeedbackMouseExited(evt);
            }
        });

        linkOurSite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkOurSite.setForeground(new java.awt.Color(90, 158, 226));
        linkOurSite.setText("Our Site");
        linkOurSite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkOurSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkOurSiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkOurSiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkOurSiteMouseExited(evt);
            }
        });

        labelLastUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLastUpdate.setText("Lastest Update :");

        linkDeveloper.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkDeveloper.setForeground(new java.awt.Color(90, 158, 226));
        linkDeveloper.setText("Click here");
        linkDeveloper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkDeveloper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkDeveloperMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkDeveloperMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkDeveloperMouseExited(evt);
            }
        });

        labelAdditional.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAdditional.setText("Additional Information");

        linkAboutSketchProject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkAboutSketchProject.setForeground(new java.awt.Color(90, 158, 226));
        linkAboutSketchProject.setText("About Sketch Project Studio");
        linkAboutSketchProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkAboutSketchProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkAboutSketchProjectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkAboutSketchProjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkAboutSketchProjectMouseExited(evt);
            }
        });

        linkDeveloperServices.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkDeveloperServices.setForeground(new java.awt.Color(90, 158, 226));
        linkDeveloperServices.setText("Developer Services");
        linkDeveloperServices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkDeveloperServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkDeveloperServicesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkDeveloperServicesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkDeveloperServicesMouseExited(evt);
            }
        });

        linkMeetOursTeam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linkMeetOursTeam.setForeground(new java.awt.Color(90, 158, 226));
        linkMeetOursTeam.setText("Meets OursTeam");
        linkMeetOursTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkMeetOursTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkMeetOursTeamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkMeetOursTeamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkMeetOursTeamMouseExited(evt);
            }
        });

        labelSystem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSystem.setText("System Core");

        labelOs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelOs.setForeground(new java.awt.Color(90, 158, 226));
        labelOs.setText("You Running on Windows 7");

        labelOsVersion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelOsVersion.setForeground(new java.awt.Color(90, 158, 226));
        labelOsVersion.setText("Version: 6.1");

        labelArch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelArch.setForeground(new java.awt.Color(90, 158, 226));
        labelArch.setText("Arch: amd64");

        labelUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelUser.setForeground(new java.awt.Color(90, 158, 226));
        labelUser.setText("User : Angga");

        labelApplication.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelApplication.setText("Application");

        labelCodename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCodename.setForeground(new java.awt.Color(90, 158, 226));
        labelCodename.setText("Code Name Avia");

        labelVendor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVendor.setForeground(new java.awt.Color(90, 158, 226));
        labelVendor.setText("Oracle Technology");

        labelVendorVersion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVendorVersion.setForeground(new java.awt.Color(90, 158, 226));
        labelVendorVersion.setText("JDK 8.1");

        labelSpecification.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSpecification.setForeground(new java.awt.Color(90, 158, 226));
        labelSpecification.setText("JDK 8.1");

        labelVm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVm.setForeground(new java.awt.Color(90, 158, 226));
        labelVm.setText("Oracle Technology");

        iconSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconChip.png"))); // NOI18N

        iconInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconInfo.png"))); // NOI18N

        iconService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconServices.png"))); // NOI18N

        iconHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconQuestion.png"))); // NOI18N

        iconApplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sketchproject/mbapp/assets/AssetsMenu/IconComputer.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(iconInformation)
                            .add(iconHelp)
                            .add(iconService))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(linkAboutSketchProject)
                            .add(linkDeveloperServices)
                            .add(linkMeetOursTeam)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(linkOurSite)
                                    .add(layout.createSequentialGroup()
                                        .add(21, 21, 21)
                                        .add(labelLastUpdate)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(linkDeveloper))
                                    .add(labelAdditional)
                                    .add(linkOpenHelp)
                                    .add(labelHelp)
                                    .add(labelCustomerCare)
                                    .add(linkSupportRequest)
                                    .add(linkSendFeedback)
                                    .add(linkQuickSolution)
                                    .add(linkSearchInternet))
                                .add(54, 54, 54)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(iconApplication)
                                    .add(iconSystem))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(labelSystem)
                                    .add(labelOs)
                                    .add(labelOsVersion)
                                    .add(labelArch)
                                    .add(labelUser)
                                    .add(labelApplication)
                                    .add(labelCodename)
                                    .add(labelVendor)
                                    .add(labelVendorVersion)
                                    .add(labelVm)
                                    .add(labelSpecification)))))
                    .add(jLabel2)
                    .add(jLabel1))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(0, 0, 0)
                .add(jLabel2)
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(labelApplication)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelOs)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelOsVersion)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelArch)
                        .add(4, 4, 4)
                        .add(labelUser)
                        .add(17, 17, 17)
                        .add(labelSystem)
                        .add(7, 7, 7)
                        .add(labelCodename)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelVendor)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelVendorVersion)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelVm)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelSpecification))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(layout.createSequentialGroup()
                                .add(iconApplication)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(iconSystem))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(labelHelp)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(linkOpenHelp))
                                    .add(iconHelp))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(linkQuickSolution)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(linkSearchInternet)
                                .add(20, 20, 20)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(labelCustomerCare)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(linkSupportRequest))
                                    .add(iconService))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(linkSendFeedback)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(linkOurSite)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(labelLastUpdate)
                            .add(linkDeveloper))
                        .add(16, 16, 16)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(labelAdditional)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(linkAboutSketchProject))
                            .add(iconInformation))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(linkDeveloperServices)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(linkMeetOursTeam)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void linkOpenHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOpenHelpMouseEntered
        linkOpenHelp.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkOpenHelpMouseEntered

    private void linkQuickSolutionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkQuickSolutionMouseEntered
        linkQuickSolution.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkQuickSolutionMouseEntered

    private void linkOpenHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOpenHelpMouseExited
        linkOpenHelp.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkOpenHelpMouseExited

    private void linkQuickSolutionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkQuickSolutionMouseExited
        linkQuickSolution.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkQuickSolutionMouseExited

    private void linkSearchInternetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSearchInternetMouseEntered
        linkSearchInternet.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkSearchInternetMouseEntered

    private void linkSearchInternetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSearchInternetMouseExited
        linkSearchInternet.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkSearchInternetMouseExited

    private void linkSupportRequestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSupportRequestMouseEntered
        linkSupportRequest.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkSupportRequestMouseEntered

    private void linkSupportRequestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSupportRequestMouseExited
        linkSupportRequest.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkSupportRequestMouseExited

    private void linkSendFeedbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSendFeedbackMouseEntered
        linkSendFeedback.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkSendFeedbackMouseEntered

    private void linkSendFeedbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSendFeedbackMouseExited
        linkSendFeedback.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkSendFeedbackMouseExited

    private void linkOurSiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOurSiteMouseEntered
        linkOurSite.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkOurSiteMouseEntered

    private void linkOurSiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOurSiteMouseExited
        linkOurSite.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkOurSiteMouseExited

    private void linkAboutSketchProjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkAboutSketchProjectMouseEntered
        linkAboutSketchProject.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkAboutSketchProjectMouseEntered

    private void linkAboutSketchProjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkAboutSketchProjectMouseExited
        linkAboutSketchProject.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkAboutSketchProjectMouseExited

    private void linkDeveloperServicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperServicesMouseEntered
        linkDeveloperServices.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkDeveloperServicesMouseEntered

    private void linkDeveloperServicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperServicesMouseExited
        linkDeveloperServices.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkDeveloperServicesMouseExited

    private void linkMeetOursTeamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMeetOursTeamMouseEntered
        linkMeetOursTeam.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkMeetOursTeamMouseEntered

    private void linkMeetOursTeamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMeetOursTeamMouseExited
        linkMeetOursTeam.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkMeetOursTeamMouseExited

    private void linkDeveloperMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperMouseEntered
        linkDeveloper.setForeground(new java.awt.Color(138, 196, 255));
    }//GEN-LAST:event_linkDeveloperMouseEntered

    private void linkDeveloperMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperMouseExited
        linkDeveloper.setForeground(new java.awt.Color(90, 158, 226));
    }//GEN-LAST:event_linkDeveloperMouseExited

    private void linkSearchInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSearchInternetMouseClicked
        BrowserControl.displayURL("https://www.google.co.id/search?q=credits");
    }//GEN-LAST:event_linkSearchInternetMouseClicked

    private void linkSupportRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSupportRequestMouseClicked
        BrowserControl.displayURL("http://microbusinessapp.sketchdeveloper.com/support");
    }//GEN-LAST:event_linkSupportRequestMouseClicked

    private void linkSendFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkSendFeedbackMouseClicked
        BrowserControl.displayURL("http://microbusinessapp.sketchdeveloper.com/feedback");
    }//GEN-LAST:event_linkSendFeedbackMouseClicked

    private void linkOurSiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOurSiteMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com");
    }//GEN-LAST:event_linkOurSiteMouseClicked

    private void linkDeveloperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com/news");
    }//GEN-LAST:event_linkDeveloperMouseClicked

    private void linkAboutSketchProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkAboutSketchProjectMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com/about");
    }//GEN-LAST:event_linkAboutSketchProjectMouseClicked

    private void linkDeveloperServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeveloperServicesMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com/services");
    }//GEN-LAST:event_linkDeveloperServicesMouseClicked

    private void linkMeetOursTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMeetOursTeamMouseClicked
        BrowserControl.displayURL("http://www.sketchdeveloper.com/ourteam");
    }//GEN-LAST:event_linkMeetOursTeamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconApplication;
    private javax.swing.JLabel iconHelp;
    private javax.swing.JLabel iconInformation;
    private javax.swing.JLabel iconService;
    private javax.swing.JLabel iconSystem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAdditional;
    private javax.swing.JLabel labelApplication;
    private javax.swing.JLabel labelArch;
    private javax.swing.JLabel labelCodename;
    private javax.swing.JLabel labelCustomerCare;
    private javax.swing.JLabel labelHelp;
    private javax.swing.JLabel labelLastUpdate;
    private javax.swing.JLabel labelOs;
    private javax.swing.JLabel labelOsVersion;
    private javax.swing.JLabel labelSpecification;
    private javax.swing.JLabel labelSystem;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelVendor;
    private javax.swing.JLabel labelVendorVersion;
    private javax.swing.JLabel labelVm;
    private javax.swing.JLabel linkAboutSketchProject;
    private javax.swing.JLabel linkDeveloper;
    private javax.swing.JLabel linkDeveloperServices;
    private javax.swing.JLabel linkMeetOursTeam;
    private javax.swing.JLabel linkOpenHelp;
    private javax.swing.JLabel linkOurSite;
    private javax.swing.JLabel linkQuickSolution;
    private javax.swing.JLabel linkSearchInternet;
    private javax.swing.JLabel linkSendFeedback;
    private javax.swing.JLabel linkSupportRequest;
    // End of variables declaration//GEN-END:variables

}
